{{- $sa := (default dict .Values.serviceAccount) -}}
{{- if (default false $sa.create) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "frontend.fullname" .) $sa.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
{{- end }}