apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.DB_URL }}: "CHANGE_ME"
  {{ .Values.secret.keys.DB_USERNAME }}: "CHANGE_ME"
  {{ .Values.secret.keys.DB_PASSWORD }}: "CHANGE_ME"
  {{ .Values.secret.keys.AWS_ACCESS_KEY }}: "CHANGE_ME"
  {{ .Values.secret.keys.AWS_SECRET_KEY }}: "CHANGE_ME"
  {{ .Values.secret.keys.AWS_REGION }}: "ap-northeast-2"
  {{ .Values.secret.keys.AWS_BUCKET }}: "wafer-bucket"