apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: 9000
    {{- if .Values.service.exposeConsole }}
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: 9001
    {{- end }}