spring.application.name=codecobain-backend

server.port=8080

spring.profiles.active=ai-test
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ============== AWS S3 bucket ============

cloud.aws.s3.bucket=${AWS_S3_BUCKET}
cloud.aws.region.static=${AWS_REGION}




# =============== database ==================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



#========= AI server ============
ai.server.url=${AI_SERVER_URL}
ai.endpoint.predict=/predict-image

# ======== wafer image for test ===========
file.upload-dir=src/main/resources/test-wafer