spring.application.name=codecobain-backend

server.port=8080

spring.profiles.active=ai-test
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ============== AWS S3 bucket ============



cloud.aws.enabled=false

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
cloud.aws.region.static=${AWS_REGION:}
cloud.aws.s3.bucket=${AWS_BUCKET:}


# =============== ?? h2 database ==================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#========= AI server ============
ai.server.url=${AI_SERVER_URL://http://localhost:8000}
ai.endpoint.predict=/predict-image

# ======== wafer image for test ===========
file.upload-dir=src/main/resources/test-wafer



# healthpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

